### PR TITLE
Updating MAIPPE plant schema

### PR DESCRIPTION
**Pull request by bedroesb**
- [x] Adding descriptions from MIAPPE
- [x] Adding descriptions from GSC MIxS
- [x] Adding descriptions from ENA Plant
- [x] Adding examples
- [ ] Adding synonym attribute
- [x] We wanted to sort the attributes based on their them

Some questions: 
- Do we still include the MIAPPE attribute ID?
- based on the descriptions it is still not 100% clear to me what the difference is between `biological material` and `material source`

### CODE REVIEW

**Comment by bedroesb** [comment]
@sebeier and @cpommier I will today add the examples, could you help out with the other stuff?

**Comment by sebeier** [comment]
I will do the sorting of attributes

**Comment by bedroesb** [comment]
@sebeier great! I will ping you when I am done with the descriptions.

**Comment by bedroesb** [comment]
@sebeier I am done with the descriptions, I am just not sure if I made a PR against the right branch...

**Comment by bedroesb** [comment]
@sebeier Thank you for contributing! I think I will reopen this PR because I pulled in some merge conflicts ....

**Comment by theisuru** [comment]
@bedroesb could you please change the base branch from `master` to `dev`. We make all pull request agains `EBIBioSamples:dev`

**Comment by bedroesb** [comment]
@theisuru done! @cpommier gives his approval we can merge this :)

**Pull request merged**
