### PR TITLE
bsd-716: use gitlab environments to maintain deployed environments

### PR DESCRIPTION
**Pull request by amnonkhen**
use gitlab environments to maintain deployment records
see EBIBioSamples/biosamples-v4#716

### CODE REVIEW

**Comment by theisuru** [comment]
Looks good to me. We can test it in the wwwdev first, after fixing the existing erros. 

Could I ask, what is the purpose of the `environment`?

**Comment by amnonkhen** [comment]
Thanks. Good questions.
[Gitlab environments](https://archives.docs.gitlab.com/16.9/ee/ci/environments/index.html) allow the team to track:

1. the version deployed in each environment
2. which pipeline execution is the one that deployed that version to the environment
3. the user that made it 
4. the time it happened
5. it maintains a like to the environment for easy access

Here is an example from HCA:

image

These are the basics. It also has some integration with k8s.

**Comment by dipayan1985** [comment]
The yaml has some syntax errors that need to be looked into.
`jobs:deploy-production-solr config key may not be used with `rules`: only`

@amnonkhen I have a few things to work on today so will setup 15 mins with you on Monday to discuss. Thank you for the changes.

**Comment by amnonkhen** [comment]
only:refs is [deprecated](https://archives.docs.gitlab.com/16.9/ee/ci/yaml/index.html#onlyrefs--exceptrefs) but still working.

**Review by dipayan1985 — APPROVED** [review]

**Pull request merged**
